##
## This file is part of the libopencm3 project.
##
## Copyright (C) 2023 Lars Boegild Thomsen <lth@stm32world.com>
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this library.  If not, see <http://www.gnu.org/licenses/>.
##

BINARY = can

LDSCRIPT = ../mcustm32f405.ld


include ../../Makefile.include

OPT = -Og
